version: '3.9'
volumes:
  node_modules:
services:
  app:
    container_name: react-native-sandbox
    build: .
    command: npm run web
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - '8081:8081'
